version: '2'
services:
  dashboard:
    build: 
      dockerfile: ./Dockerfile
      context: .
    image: itglobal/dashboard
    container_name: dashboard
    restart: always
    
    volumes: 
      - ./config:/app/config

    ports:
      - 8000:8000

    environment: 
      - DASH_ENDPOINT=0.0.0.0:8000
      - DASH_CONFIG=/app/config/dashboard.json